/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class activitytest_example_com_gpio_GpioAduio */

#ifndef _Included_activitytest_example_com_gpio_GpioAduio
#define _Included_activitytest_example_com_gpio_GpioAduio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     activitytest_example_com_gpio_GpioAduio
 * Method:    enableSpk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_activitytest_example_com_gpio_GpioAduio_enableSpk
  (JNIEnv *, jclass);

/*
 * Class:     activitytest_example_com_gpio_GpioAduio
 * Method:    disableSpk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_activitytest_example_com_gpio_GpioAduio_disableSpk
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
